org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
org.gradle.warning.mode=summary
org.gradle.parallel=true
org.gradle.workers.max=2
kotlin.code.style=official
kotlin.incremental=false
android.builtInKotlin=false
android.newDsl=false
